/*
  Generated by scripts/music-samples.py; edit the table there, not here.
  Which recorded notes exist for each instrument of the soundtrack (MIDI
  numbers, as measured, not as the source files were named), and how many
  cents each recording sits off true pitch. The files are
  public/os/music/<inst>/<midi>.mp3, CC0, credited in the LICENSE.md there.
*/

export interface PitchedSet { notes: readonly number[]; cents: readonly number[] }
export interface HitSet { hits: number }

export const PITCHED = {
  piano: { notes: [37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95], cents: [-8.5, -3.3, 2.6, -0.4, -5.9, -2.6, -1.9, 4.9, 0.8, 0.0, 2.1, 0.5, 2.2, 4.2, 1.6, 2.0, 1.3, 6.4, 4.2, 1.5, 4.1, 6.4, 5.6, 9.9, 11.6, 5.4, 12.8, 10.9, 17.8, 15.2] },
} satisfies Record<string, PitchedSet>

export const HITS = {
} satisfies Record<string, HitSet>

export type PitchedId = keyof typeof PITCHED
export type HitId = keyof typeof HITS
